#!/bin/bash
set -euo pipefail

OLD_PG_VERSION="${OLD_PG_VERSION:?OLD_PG_VERSION env var must be set}"
NEW_PG_VERSION="${NEW_PG_VERSION:?NEW_PG_VERSION env var must be set}"
OLD_DATA_DIR="/var/lib/postgresql/${OLD_PG_VERSION}/main"
NEW_DATA_DIR="/var/lib/postgresql/${NEW_PG_VERSION}/main"
OLD_BIN="/usr/lib/postgresql/${OLD_PG_VERSION}/bin"
NEW_BIN="/usr/lib/postgresql/${NEW_PG_VERSION}/bin"
WORK_DIR="/var/lib/postgresql"

# pg_upgrade writes log files and post-upgrade scripts (analyze_new_cluster.sh,
# delete_old_cluster.sh) to the current working directory, which must be
# writable by the postgres user.
cd "${WORK_DIR}"

# ── Helpers ──────────────────────────────────────────────────────────────────

hr() { printf '%.0s─' {1..70}; echo; }

show_cluster_snapshot() {
  local label="$1"
  local data_dir="$2"

  echo ""
  hr
  echo "  ${label}"
  hr
  printf "  %-20s %s\n" "Path:"  "${data_dir}"
  printf "  %-20s %s\n" "Total size:" "$(du -sh "${data_dir}" 2>/dev/null | cut -f1)"
  echo ""

  echo "  Directories:"
  while IFS= read -r line; do
    size=$(echo "$line" | awk '{print $1}')
    dir=$(echo "$line"  | awk '{print $2}' | sed "s|${data_dir}/||")
    printf "    %-40s %s\n" "${dir}/" "${size}"
  done < <(du -sh "${data_dir}"/*/  2>/dev/null | sort -rh)

  echo ""
  echo "  Config / control files:"
  while IFS= read -r f; do
    size=$(du -sh "${f}" 2>/dev/null | cut -f1)
    printf "    %-40s %s\n" "$(basename "${f}")" "${size}"
  done < <(find "${data_dir}" -maxdepth 1 -type f | sort)

  hr
}

show_rename_notes() {
  # Highlight structural renames introduced between PG 9.x and PG 10+
  # that pg_upgrade handles transparently but are worth knowing about.
  local old_v="$1"
  local new_v="$2"

  local old_major
  old_major=$(echo "${old_v}" | cut -d. -f1)

  if [ "${old_major}" -lt 10 ]; then
    echo ""
    echo "  Notable structural changes applied during this upgrade:"
    printf "    %-30s → %s\n" "pg_xlog/"  "pg_wal/   (WAL directory, renamed in PG 10)"
    printf "    %-30s → %s\n" "pg_clog/"  "pg_xact/  (transaction status, renamed in PG 10)"
    printf "    %-30s → %s\n" "pg_log/"   "log/      (server log directory, renamed in PG 10)"
  fi
}

show_generated_scripts() {
  echo ""
  echo "  Post-upgrade scripts generated by pg_upgrade:"
  for script in analyze_new_cluster.sh delete_old_cluster.sh; do
    if [ -f "${WORK_DIR}/${script}" ]; then
      printf "    ✓ %-40s (in %s)\n" "${script}" "${WORK_DIR}"
    else
      printf "    ✗ %-40s (not found)\n" "${script}"
    fi
  done
  echo ""
  echo "  Run analyze_new_cluster.sh on the new cluster to refresh planner statistics."
  echo "  Run delete_old_cluster.sh after verifying production is healthy."
}

# ── Step 1: Snapshot old cluster ─────────────────────────────────────────────

echo ""
echo "==> Snapshotting old cluster before upgrade"
show_cluster_snapshot "Old cluster — PostgreSQL ${OLD_PG_VERSION}" "${OLD_DATA_DIR}"

UPGRADE_START=$(date +%s)

# ── Step 2: Initialise new cluster ───────────────────────────────────────────

echo ""
echo "==> Initializing PostgreSQL ${NEW_PG_VERSION} cluster at ${NEW_DATA_DIR}"
"${NEW_BIN}/initdb" \
  -D "${NEW_DATA_DIR}" \
  --encoding=UTF8 \
  --locale=en_US.UTF-8

# ── Step 3: Compatibility check ──────────────────────────────────────────────

echo ""
echo "==> Running pg_upgrade compatibility check (dry run)"
"${NEW_BIN}/pg_upgrade" \
  -b "${OLD_BIN}" \
  -B "${NEW_BIN}" \
  -d "${OLD_DATA_DIR}" \
  -D "${NEW_DATA_DIR}" \
  --check

# ── Step 4: Real upgrade ─────────────────────────────────────────────────────

echo ""
echo "==> Compatibility check passed. Running pg_upgrade"
"${NEW_BIN}/pg_upgrade" \
  -b "${OLD_BIN}" \
  -B "${NEW_BIN}" \
  -d "${OLD_DATA_DIR}" \
  -D "${NEW_DATA_DIR}"

UPGRADE_END=$(date +%s)
UPGRADE_SECS=$(( UPGRADE_END - UPGRADE_START ))

# ── Step 5: Post-upgrade ANALYZE ─────────────────────────────────────────────

echo ""
echo "==> Running post-upgrade ANALYZE on all databases"
if [ -f "${WORK_DIR}/analyze_new_cluster.sh" ]; then
  bash "${WORK_DIR}/analyze_new_cluster.sh"
else
  echo "    (analyze_new_cluster.sh not found — skipping)"
fi

# ── Step 6: Summary report ───────────────────────────────────────────────────

echo ""
echo "==> Snapshotting new cluster after upgrade"
show_cluster_snapshot "New cluster — PostgreSQL ${NEW_PG_VERSION}" "${NEW_DATA_DIR}"
show_rename_notes "${OLD_PG_VERSION}" "${NEW_PG_VERSION}"
show_generated_scripts

OLD_SIZE_KB=$(du -sk "${OLD_DATA_DIR}" 2>/dev/null | cut -f1)
NEW_SIZE_KB=$(du -sk "${NEW_DATA_DIR}" 2>/dev/null | cut -f1)
OLD_SIZE_HR=$(du -sh "${OLD_DATA_DIR}" 2>/dev/null | cut -f1)
NEW_SIZE_HR=$(du -sh "${NEW_DATA_DIR}" 2>/dev/null | cut -f1)

if [ "${OLD_SIZE_KB}" -gt 0 ]; then
  OVERHEAD=$(( (NEW_SIZE_KB - OLD_SIZE_KB) * 100 / OLD_SIZE_KB ))
else
  OVERHEAD=0
fi

echo ""
hr
echo "  Upgrade complete"
hr
printf "  %-30s %s → %s  (%+d%%)\n" "Cluster size:" "${OLD_SIZE_HR}" "${NEW_SIZE_HR}" "${OVERHEAD}"
printf "  %-30s %ds\n" "Upgrade duration:" "${UPGRADE_SECS}"
printf "  %-30s %s → %s\n" "PostgreSQL version:" "${OLD_PG_VERSION}" "${NEW_PG_VERSION}"
hr
